'use client';
import { useEffect,useState } from 'react';
import type { MaintenanceModel } from './use-maintenance';
import type { Row } from '../../lib/maintenance/types';
function template(name:string,reference:string,quantity:number,site:string,sender:string){return `Bonjour,\n\nPourriez-vous nous transmettre un devis pour le produit suivant :\n\nProduit : ${name||'[nom du produit]'}\nRéférence : ${reference||'[référence à préciser]'}\nQuantité : ${quantity}\nSite : ${site}\n\nMerci de préciser le prix, le délai de livraison, les frais de transport et la durée de validité du devis.\n\nCordialement,\n${sender||'Service maintenance'}`;}
export function QuoteMail({model,order,onClose}:{model:MaintenanceModel;order?:Row;onClose:()=>void}){
 const [access,setAccess]=useState<any>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[locked,setLocked]=useState(false);
 const [name,setName]=useState(order?.name||''),[reference,setReference]=useState(order?.reference||''),[supplier,setSupplier]=useState(order?.supplier||''),[quantity,setQuantity]=useState(order?.quantity||1),[to,setTo]=useState(''),[subject,setSubject]=useState('Demande de devis — '+(order?.name||'pièce de maintenance'));
 const [body,setBody]=useState(()=>template(order?.name||'',order?.reference||'',order?.quantity||1,model.sites.find(s=>s.id===model.site)?.name||'',model.user.name)),[id]=useState(()=>crypto.randomUUID());
 async function load(){try{const r=await fetch('/api/quote-mail?site='+encodeURIComponent(model.site)),d:any=await r.json();if(!r.ok)throw Error(d.error);setAccess(d);return d;}catch(e){setError(e instanceof Error?e.message:'Réglages indisponibles.');return null;}}
 useEffect(()=>{load();},[model.site]);
 async function send(){if(busy||locked)return;setBusy(true);setError('');try{const r=await fetch('/api/quote-mail',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,site:model.site,to,subject,body,details:{name,reference,quantity,supplier,orderId:order?.id||'',machine:order?.machine||model.selected?.id||''}})}),d:any=await r.json();if(!r.ok)throw Error(d.error);setMessage(d.message);setLocked(true);await model.refresh();window.dispatchEvent(new Event('quote-requests-changed'));onClose();}catch(e){setError(e instanceof Error?e.message:'Envoi impossible.');}finally{setBusy(false);}}
 async function openMailbox(){const latest=await load();if(!latest?.canSend||!latest.settings?.sender_email){setError('Votre responsable doit vous autoriser et renseigner une adresse d’expédition.');return;}window.location.href='mailto:'+encodeURIComponent(to)+'?subject='+encodeURIComponent(subject)+'&body='+encodeURIComponent(body);setMessage('Brouillon ouvert dans votre messagerie. Sélectionnez l’adresse d’expédition du site puis vérifiez le message avant de l’envoyer.');}
 const canSend=access?.canSubmit && access?.settings?.sender_email;
 const requiresApproval=model.user.role==='technician'&&!access?.canSend;
 return <div className="overlay"><form className="modal intervention-modal quote-mail-fields" onSubmit={e=>{e.preventDefault();send();}}><div className="panel-head"><h2>Demande de devis par mail</h2><button type="button" onClick={onClose} disabled={busy}>Fermer</button></div><fieldset disabled={busy||locked} className="report-fields"><label>Adresse d’expédition du site<input readOnly value={access?.settings?.sender_email||''} placeholder="À renseigner par le responsable maintenance"/><small>Réglée par le responsable. Les réponses seront adressées à cette boîte mail. Le service d’envoi peut utiliser une adresse technique si le domaine n’est pas autorisé.</small></label><label>Destinataire *<input required type="email" maxLength={254} value={to} onChange={e=>setTo(e.target.value)} placeholder="devis@fournisseur.fr"/></label><label>Fournisseur<input maxLength={200} value={supplier} onChange={e=>setSupplier(e.target.value)} placeholder="Nom du fournisseur"/></label><label>Produit *<input required maxLength={150} value={name} onChange={e=>setName(e.target.value)}/></label><label>Référence<input maxLength={200} value={reference} onChange={e=>setReference(e.target.value)}/></label><label>Quantité<input required type="number" min={1} max={1000000} value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label><button type="button" onClick={()=>{setBody(template(name,reference,quantity,model.sites.find(s=>s.id===model.site)?.name||'',access?.settings?.sender_name||model.user.name));setSubject('Demande de devis — '+(name||'pièce de maintenance'));}}>Préremplir le message avec ces informations</button><label>Objet *<input required maxLength={200} value={subject} onChange={e=>setSubject(e.target.value)}/></label><label>Message *<textarea required maxLength={15000} value={body} onChange={e=>setBody(e.target.value)}/></label></fieldset>
 {access&&!access.canSend&&model.user.role==='technician'&&<p className="muted">Vous pouvez soumettre cette demande. Le responsable du site ou le directeur technique doit la valider avant son envoi au fournisseur.</p>}{access&&!access.mailReady&&<p className="muted">L’envoi intégré n’est pas encore activé. {model.user.role==='technician'?'Le message peut être préparé ici ; il sera soumis au responsable après activation du service mail.':'Vous pouvez préparer le brouillon dans votre messagerie avec l’adresse autorisée.'}</p>}{canSend&&!access.settings.confirmed&&<p className="muted">L’adresse d’expédition doit être confirmée pour l’envoi intégré.</p>}{error&&<p className="error" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
 <div className="actions"><button className="primary" type="submit" disabled={busy||locked||!canSend||!access?.settings?.confirmed||!access?.mailReady}>{requiresApproval?'Soumettre au responsable pour validation':'Envoyer depuis l’application'}</button>{model.user.role!=='technician'&&<button type="button" disabled={busy||locked||!canSend||!to||!subject||!body} onClick={openMailbox}>Ouvrir dans ma messagerie</button>}</div>{requiresApproval&&<p>La demande sera disponible dans « Demandes de devis — validations et historique » pour le responsable du site et le directeur technique. Le fournisseur ne le recevra qu’après validation.</p>}<small>Après l’envoi au fournisseur, un devis est automatiquement créé au statut « Devis ». Si la demande concerne un devis existant, celui-ci est conservé sans doublon. Le stock sera mis à jour uniquement à la réception. Vous pourrez enregistrer le devis reçu avec son PDF.</small>
 </form></div>;
}
export function QuoteMailPermissions({model}:{model:MaintenanceModel}){
 const [data,setData]=useState<any>(null),[email,setEmail]=useState(''),[name,setName]=useState('Maintenance'),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){try{const r=await fetch('/api/quote-mail?site='+encodeURIComponent(model.site)),d:any=await r.json();if(!r.ok)throw Error(d.error);setData(d);setEmail(d.settings?.sender_email||'');setName(d.settings?.sender_name||'Maintenance');}catch(e){setError(e instanceof Error?e.message:'Réglages indisponibles.');}}
 useEffect(()=>{load();},[model.site]);
 async function post(input:any){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/quote-mail',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...input,site:model.site})}),d:any=await r.json();if(!r.ok)throw Error(d.error);setMessage(d.message||'Autorisation mise à jour.');await load();}catch(e){setError(e instanceof Error?e.message:'Modification impossible.');}finally{setBusy(false);}}
 if(model.readOnly || !['admin','director','manager'].includes(model.user.role))return null;
 return <section className="panel"><details><summary>Adresse d’expédition des devis</summary>{data?.canManage&&<><form onSubmit={e=>{e.preventDefault();post({action:'settings',email,name,revision:data.settings?.revision||0});}}><label>Adresse mail par défaut<input required type="email" maxLength={254} value={email} onChange={e=>setEmail(e.target.value)} disabled={busy}/></label><label>Nom d’expéditeur<input required maxLength={100} value={name} onChange={e=>setName(e.target.value)} disabled={busy}/></label><button type="submit" disabled={busy}>Enregistrer l’adresse</button></form>{data.settings?.sender_email&&<p>{data.settings.confirmed?'Adresse confirmée.':'Adresse à confirmer.'}</p>}{data.settings?.sender_email&&!data.settings.confirmed&&<button disabled={busy||!data.mailReady} onClick={()=>post({action:'confirm-sender'})}>Envoyer le lien de confirmation</button>}<p>Les autorisations d’envoi des techniciens se règlent dans leur fiche utilisateur.</p>{!data.mailReady&&<p className="muted">Le service mail reste à configurer. La préparation de brouillons dans votre messagerie est disponible.</p>}</>}{error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status">{message}</p>}</details></section>;
}
