'use client';
import { useEffect,useState } from 'react';
import type { MaintenanceModel } from './use-maintenance';
const stateNames:Record<string,string>={pending:'En attente de validation',approved:'Validée',rejected:'Refusée'};
export function QuoteReview({id,onClose,onChanged}:{id:string;onClose:()=>void;onChanged?:()=>void}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[editing,setEditing]=useState<any>(null);
 async function load(){try{const r=await fetch('/api/quote-mail/requests?id='+encodeURIComponent(id)),d:any=await r.json();if(!r.ok)throw Error(d.error);setData(d);}catch(e){setError(e instanceof Error?e.message:'Demande indisponible.');}}
 useEffect(()=>{load();},[id]);
 async function decide(action:'approve'|'reject'){setBusy(true);setError('');try{const r=await fetch('/api/quote-mail/requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,action,revision:data.request.revision})}),d:any=await r.json();if(!r.ok)throw Error(d.error);setMessage(d.message);await load();onChanged?.();}catch(e){setError(e instanceof Error?e.message:'Décision impossible.');}finally{setBusy(false);}}
 function beginEdit(){const q=data.request,d=q.order_data?JSON.parse(q.order_data):{};setEditing({to:q.recipient,subject:q.subject,body:q.body,name:d.name||q.body.match(/^Produit : (.+)$/m)?.[1]||'',reference:d.reference||q.body.match(/^Référence : (.*)$/m)?.[1]||'',quantity:d.quantity||Number(q.body.match(/^Quantité : (\d+)/m)?.[1])||1,supplier:d.supplier||q.recipient});}
 async function saveEdit(){setBusy(true);setError('');try{const r=await fetch('/api/quote-mail/requests',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,revision:data.request.revision,to:editing.to,subject:editing.subject,body:editing.body,details:{name:editing.name,reference:editing.reference,quantity:Number(editing.quantity),supplier:editing.supplier}})}),d:any=await r.json();if(!r.ok)throw Error(d.error);setMessage(d.message);setEditing(null);await load();onChanged?.();}catch(e){setError(e instanceof Error?e.message:'Modification impossible.');}finally{setBusy(false);}}
 const q=data?.request;
 return <div className="overlay"><section className="modal intervention-modal"><div className="panel-head"><h2>Validation d’une demande de devis</h2><button disabled={busy} onClick={onClose}>Fermer</button></div>{q?<>{q.state==='pending'&&!editing&&<button disabled={busy} onClick={beginEdit}>Modifier la demande</button>}{editing&&<form onSubmit={e=>{e.preventDefault();saveEdit();}}>{[['to','Destinataire'],['name','Produit'],['reference','Référence'],['supplier','Fournisseur'],['subject','Objet']].map(([key,label])=><label key={key}>{label}<input required={key!=='reference'&&key!=='supplier'} type={key==='to'?'email':'text'} maxLength={key==='subject'||key==='supplier'||key==='reference'?200:key==='name'?150:254} value={editing[key]} onChange={e=>setEditing({...editing,[key]:e.target.value})} disabled={busy}/></label>)}<label>Quantité<input required type="number" min={1} max={1000000} value={editing.quantity} onChange={e=>setEditing({...editing,quantity:e.target.value})} disabled={busy}/></label><label>Message<textarea required maxLength={15000} value={editing.body} onChange={e=>setEditing({...editing,body:e.target.value})} disabled={busy}/></label><button type="submit" disabled={busy}>Enregistrer les modifications</button><button type="button" disabled={busy} onClick={()=>setEditing(null)}>Annuler</button></form>}<p>Rédigée par {q.author||'Ancien utilisateur'} · {stateNames[q.state]}</p><p><strong>Expéditeur / adresse de réponse :</strong> {q.sender_email}</p><p><strong>Destinataire :</strong> {q.recipient}</p><p><strong>Objet :</strong> {q.subject}</p><div className="panel plan-description">{q.body}</div>{q.state==='pending'&&<p>Aucun mail n’est envoyé au fournisseur avant validation.</p>}{data.canApprove&&q.state==='pending'&&!editing&&<div className="actions"><button className="primary" disabled={busy} onClick={()=>decide('approve')}>Valider et envoyer au fournisseur</button><button className="danger" disabled={busy} onClick={()=>decide('reject')}>Refuser</button></div>}</>:<p>Chargement…</p>}{error&&<p role="alert" className="error">{error}</p>}{message&&<p role="status">{message}</p>}</section></div>;
}
export function QuoteRequests({model}:{model:MaintenanceModel}){
 const [data,setData]=useState<any>(null),[selected,setSelected]=useState(''),[error,setError]=useState(''),[deleting,setDeleting]=useState('');
 async function load(){try{const r=await fetch('/api/quote-mail/requests?site='+encodeURIComponent(model.site)),d:any=await r.json();if(!r.ok)throw Error(d.error);setData(d);if(d.created)await model.refresh();}catch(e){setError(e instanceof Error?e.message:'Demandes indisponibles.');}}
 useEffect(()=>{load();const timer=setInterval(load,15000);window.addEventListener('quote-requests-changed',load);return()=>{clearInterval(timer);window.removeEventListener('quote-requests-changed',load);};},[model.site]);
 async function remove(q:any){
  if(deleting||!window.confirm('Supprimer cette demande de devis ? Les envois en attente seront annulés. Le devis associé sera conservé et les mails déjà envoyés ne pourront pas être rappelés.'))return;
  setDeleting(q.id);setError('');
  try{const r=await fetch('/api/quote-mail/requests',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:q.id,revision:q.revision})}),d:any=await r.json();if(!r.ok)throw Error(d.error);await load();}catch(e){setError(e instanceof Error?e.message:'Suppression impossible.');}finally{setDeleting('');}
 }
 if(model.readOnly)return null;
 return <section className="panel"><details><summary>{data?.canApprove?'Demandes de devis — validations et historique':'Mes demandes de devis'}{data?.requests?.some((q:any)=>q.state==='pending')?' · '+data.requests.filter((q:any)=>q.state==='pending').length+' en attente':''}</summary>{data?.requests?.length?<div className="table-wrap"><table><thead><tr><th>Objet</th><th>Auteur</th><th>Destinataire</th><th>Validation</th><th>Envoi / devis</th><th/></tr></thead><tbody>{data.requests.map((q:any)=><tr key={q.id}><td>{q.subject}</td><td>{q.author||'Ancien utilisateur'}</td><td>{q.recipient}</td><td>{stateNames[q.state]}</td><td>{q.delivery_state==='accepted'?(q.order_id?'Envoyée · devis enregistré':'Envoyée · informations à compléter'):q.delivery_state==='review'?'Envoi à vérifier':q.delivery_state==='cancelled'?'Envoi annulé':q.state==='approved'?'En attente d’envoi':'—'}</td><td><button onClick={()=>setSelected(q.id)}>{q.state==='pending'&&data.canApprove?'Examiner / valider':'Voir le message'}</button>{(data.canApprove||q.user_id===model.user.id)&&<button className="danger" disabled={!!deleting} onClick={()=>remove(q)}>Supprimer</button>}</td></tr>)}</tbody></table></div>:<p>Aucune demande.</p>}{error&&<p className="error" role="alert">{error}</p>}</details>{selected&&<QuoteReview id={selected} onClose={()=>setSelected('')} onChanged={()=>{load();model.refresh();}}/>}</section>;
}
