import fs from 'node:fs';import path from 'node:path';import ts from 'typescript';import React from 'react';import {renderToStaticMarkup} from 'react-dom/server';import {createRequire} from 'node:module';import assert from 'node:assert/strict';
const cache=new Map();function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file);const output=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText;const require=createRequire(file),exports={};cache.set(file,exports);new Function('require','exports',output)(specifier=>{if(!specifier.startsWith('.'))return require(specifier);const base=path.resolve(path.dirname(file),specifier);return load([base,base+'.ts',base+'.tsx'].find(f=>fs.existsSync(f)))},exports);return exports;}
const {Access}=load('app/access.tsx'),{AccountProfile}=load('app/account-profile.tsx'),{AccountLink}=load('app/account-link.tsx'),{QuoteMail}=load('app/maintenance/quote-mail.tsx'),{PlanEditor}=load('app/planning/editor.tsx');
const user={id:'tech',name:'Technicien',username:'tech',role:'technician',site:'site1',email:'',change_password:1};
const access=renderToStaticMarkup(React.createElement(Access,{user,onSuccess(){}}));assert(access.includes('Adresse mail *'));assert(access.includes('type="email"'));assert(/minlength="6"/i.test(access));
const login=renderToStaticMarkup(React.createElement(Access,{onSuccess(){}}));assert(login.includes('Mot de passe oublié ?'));
const profile=renderToStaticMarkup(React.createElement(AccountProfile,{user,mailReady:false,onRefresh:async()=>{},onClose(){}}));assert(profile.includes('Photo de profil'));assert(profile.includes('Changer mon mot de passe'));assert(profile.includes('Renseignez votre adresse mail'));assert(!profile.includes('Retour à la GMAO'));assert(profile.includes('n’est pas encore activé'));
const token='a'.repeat(64),reset=renderToStaticMarkup(React.createElement(AccountLink,{link:{purpose:'reset',token},onDone(){}}));assert(reset.includes('Nouveau mot de passe'));assert(!reset.includes(token));
const model={user,site:'site1',sites:[{id:'site1',name:'Usine 1'}],machines:[],records:[],parts:[],qty(){return 0;}};
const quote=renderToStaticMarkup(React.createElement(QuoteMail,{model,order:{name:'Roulement',reference:'6200',quantity:3},onClose(){}}));assert(quote.includes('Roulement'));assert(quote.includes('6200'));assert(quote.includes('Quantité : 3'));assert(quote.includes('Soumettre au responsable pour validation'));assert(!quote.includes('Ouvrir dans ma messagerie'));
const manager=renderToStaticMarkup(React.createElement(QuoteMail,{model:{...model,user:{...user,role:'manager'}},onClose(){}}));assert(manager.includes('Ouvrir dans ma messagerie'));assert(manager.includes('Envoyer depuis l’application'));
const editor=renderToStaticMarkup(React.createElement(PlanEditor,{model,teammates:[],onClose(){},onSaved:async()=>{}}));assert(editor.includes('Alerter les personnes affectées par mail'));
console.log('PASS: first-login email, profile/photo/password controls, recovery, private reset token, quote prefilling, technician approval gate and punctual notification option.');

const {MailConfiguration}=load('app/maintenance/mail-configuration.tsx');const setup=renderToStaticMarkup(React.createElement(MailConfiguration,{global:true,onConfigured(){}}));assert(setup.includes('Connecter une boîte Outlook'));assert(!setup.includes('Resend'));const siteSetup=renderToStaticMarkup(React.createElement(MailConfiguration,{site:'site1',onConfigured(){}}));assert(siteSetup.includes('Demandes de devis'));assert(siteSetup.includes('mot de passe oublié'));console.log('PASS: separate common/site Outlook setup and automatic/quote selections.');

const {SiteMailSettings}=load('app/maintenance/site-mail-settings.tsx');const directorSettings=renderToStaticMarkup(React.createElement(SiteMailSettings,{model:{...model,user:{...user,role:'director'}},onConfigured(){}}));assert(directorSettings.includes('Site à configurer'));assert(directorSettings.includes('Adresse d’expédition des devis'));const ownSettings=renderToStaticMarkup(React.createElement(SiteMailSettings,{model:{...model,site:'other',user:{...user,role:'manager'}},onConfigured(){}}));assert(ownSettings.includes('Réglages de votre site'));assert(!ownSettings.includes('Site à configurer'));

const {OrdersView}=load('app/maintenance/orders.tsx');const orderModel={...model,tab:'Devis & achats',selected:null,readOnly:false,records:[{id:'order1',site:'site1',kind:'order',name:'Pompe',status:'Devis',quantity:1}],saving:false};const orders=renderToStaticMarkup(React.createElement(OrdersView,{model:orderModel}));assert(orders.indexOf('Devis &amp; commandes')<orders.indexOf('Mes demandes de devis'));assert(orders.includes('Passer à Commandé : Pompe'));const readOnlyOrders=renderToStaticMarkup(React.createElement(OrdersView,{model:{...orderModel,readOnly:true}}));assert(!readOnlyOrders.includes('Passer à Commandé'));

const trialAccess=renderToStaticMarkup(React.createElement(Access,{user:{...user,test_account:1},onSuccess(){}}));assert(!trialAccess.includes('Adresse mail *'));assert(trialAccess.includes('Nouveau mot de passe'));const trialProfile=renderToStaticMarkup(React.createElement(AccountProfile,{user:{...user,test_account:1},mailReady:false,onRefresh:async()=>{},onClose(){}}));assert(trialProfile.includes('Retour à la GMAO'));assert(trialProfile.includes('Compte de test'));
