import fs from 'node:fs';import path from 'node:path';import ts from 'typescript';import React from 'react';import {renderToStaticMarkup} from 'react-dom/server';import {createRequire} from 'node:module';import assert from 'node:assert/strict';
const cache=new Map();function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file);const output=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText;const require=createRequire(file),exports={};cache.set(file,exports);new Function('require','exports',output)(specifier=>{if(!specifier.startsWith('.'))return require(specifier);const base=path.resolve(path.dirname(file),specifier);return load([base,base+'.ts',base+'.tsx'].find(f=>fs.existsSync(f)))},exports);return exports;}
const {RoutineCalendar}=load('app/planning/calendar.tsx'),{PlanEditor}=load('app/planning/editor.tsx'),{ReportForm}=load('app/interventions/report-form.tsx'),{initialQuestions,interventionToday}=load('lib/interventions/types.ts');
const today=interventionToday(),model={site:'site1',machines:[{id:'m1',name:'Machine 1'}],parts:[{id:'p1',name:'Roulement',reference:'6200'}],records:[{id:'o1',site:'site1',kind:'order',name:'Devis roulement',status:'Commandé'}],qty(){return 3;},onSessionChanged(){}};
const routines=[{id:'r1',site:'site1',name:'Graissage',machine:'m1',start:today,frequency:'weekly',revision:1}],done=[{routine:'r1',date:today,actor:'Technicien',completedAt:today+'T10:00:00Z'}];
const calendar=renderToStaticMarkup(React.createElement(RoutineCalendar,{model,routines,done,onSaved:async()=>{}}));assert(calendar.includes('Graissage'));assert(calendar.includes('✓ Fait'));assert(calendar.includes('ne crée pas de rapport'));assert(calendar.includes('calendar-grid'));assert(calendar.includes('Mois précédent'));assert(calendar.includes('Ajouter une tâche'));
const plan={id:'plan1',site:'site1',name:'Remplacer le roulement',machine:'m1',date:today,time:'10:00',work:'Travaux prévus spécifiques',requirements:[{part:'p1',order:null,quantity:2}],equipment:'Nacelle',equipmentReady:false,status:'planned',revision:1,createdAt:today,ready:false,blockers:['Nacelle indisponible'],machineName:'Machine 1',parts:[{part:'p1',name:'Roulement',reference:'6200',quantity:2}]};
const editor=renderToStaticMarkup(React.createElement(PlanEditor,{model,initial:plan,onClose(){},onSaved:async()=>{}}));assert(editor.includes('Devis roulement'));assert(editor.includes('Quantité requise'));assert(editor.includes('Équipement disponible'));assert(editor.includes('ne réserve ni ne déduit'));
const report=renderToStaticMarkup(React.createElement(ReportForm,{form:{version:1,questions:initialQuestions},site:'site1',siteName:'Site 1',machines:model.machines,initialPlan:plan,onSaved(){},onClose(){},onSessionChanged(){},onRefresh(){}}));assert(report.includes('Travaux prévus spécifiques'));assert(report.includes('Remplacer le roulement'));assert(report.includes('archivée comme réalisée'));assert(report.includes('Roulement'));assert(report.includes('6200'));assert(report.includes('value="2"'));
console.log('PASS: recurring calendar and simple completion labels, plan stock/order/equipment editor and normal-report prefilling.');
const multiModel={...model,machines:[...model.machines,{id:'m2',name:'Machine 2'},{id:'m3',name:'Machine 3'}]},multiPlan={...plan,machines:['m1','m2']};
const multiEditor=renderToStaticMarkup(React.createElement(PlanEditor,{model:multiModel,initial:multiPlan,onClose(){},onSaved:async()=>{}}));assert(multiEditor.includes('Toutes les machines'));assert(multiEditor.includes('Tout décocher'));assert(multiEditor.includes('2 machine(s)'));assert(multiEditor.includes('total pour toutes les machines'));
const multiReportMarkup=renderToStaticMarkup(React.createElement(ReportForm,{form:{version:1,questions:initialQuestions},site:'site1',siteName:'Site 1',machines:multiModel.machines,initialPlan:multiPlan,onSaved(){},onClose(){},onSessionChanged(){},onRefresh(){}}));assert.match(multiReportMarkup,/checked=""\/>Machine 1/);assert.match(multiReportMarkup,/checked=""\/>Machine 2/);assert(!/checked=""\/>Machine 3/.test(multiReportMarkup));
const multiCalendar=renderToStaticMarkup(React.createElement(RoutineCalendar,{model:multiModel,routines:[{...routines[0],machines:['m1','m2']}],done,onSaved:async()=>{}}));assert(multiCalendar.includes('Machine 1, Machine 2'));
const {MaintenanceShell}=load('app/maintenance/shell.tsx');const shell=renderToStaticMarkup(React.createElement(MaintenanceShell,{model:{...multiModel,user:{name:'Test',role:'technician'},sites:[{id:'site1',name:'Site 1'}],tab:'Planning',globalAccess:false},onAccount(){},onSessionChanged(){}}));assert(shell.indexOf('>Planning</button>')<shell.indexOf('>Machines</button>'));console.log('PASS: multi-machine checkbox picker and report prefilling, calendar labels and Planning first in navigation.');
const flexiblePlan={...multiPlan,date:'',time:'',instructions:'Étape 1 : vérifier les protections.'};const flexibleEditor=renderToStaticMarkup(React.createElement(PlanEditor,{model:multiModel,initial:flexiblePlan,onClose(){},onSaved:async()=>{}}));assert(flexibleEditor.includes('Précisions pour réaliser la tâche'));assert(flexibleEditor.includes('Étape 1'));assert(flexibleEditor.includes('Date prévue (facultatif)'));assert(!/required="" type="date"/.test(flexibleEditor));
const flexibleReportMarkup=renderToStaticMarkup(React.createElement(ReportForm,{form:{version:1,questions:initialQuestions},site:'site1',siteName:'Site 1',machines:multiModel.machines,initialPlan:flexiblePlan,onSaved(){},onClose(){},onSessionChanged(){},onRefresh(){}}));assert(flexibleReportMarkup.includes('Étape 1'));assert(!flexibleReportMarkup.includes('Invalid Date'));const {planningSchedule}=load('lib/planning/routines-client.ts');assert.equal(planningSchedule(flexiblePlan),'Date à définir · Heure libre');console.log('PASS: optional schedule fields and execution instructions visible in the editor and report.');
const sharedCalendar=renderToStaticMarkup(React.createElement(RoutineCalendar,{model:multiModel,routines,done,plans:[{...multiPlan,name:'Ponctuelle datée 10h',time:'10:00'},{...multiPlan,id:'second-calendar-plan',name:'Ponctuelle datée 08h',time:'08:00',ready:true,blockers:[]},{...multiPlan,id:'undated-calendar-plan',date:'',name:'Sans date hors calendrier'},{...multiPlan,id:'other-month-plan',date:'2099-01-01',name:'Autre mois hors calendrier'},{...multiPlan,id:'completed-calendar-plan',name:'Ponctuelle déjà réalisée',status:'done'}],onOpenPlan(){},onReportPlan(){},onSaved:async()=>{}}));assert(sharedCalendar.includes('Calendrier des interventions'));assert(sharedCalendar.includes('Graissage'));assert(sharedCalendar.includes('Ponctuelle datée 10h'));assert(sharedCalendar.indexOf('Ponctuelle datée 08h')<sharedCalendar.indexOf('Ponctuelle datée 10h'));assert(sharedCalendar.includes('Réalisable'));assert(sharedCalendar.includes('En attente'));assert(sharedCalendar.includes('Voir le rapport'));assert(!sharedCalendar.includes('Sans date hors calendrier'));assert(!sharedCalendar.includes('Autre mois hors calendrier'));console.log('PASS: dated punctual interventions share the routine calendar, ordered by time, with readiness/completion actions; undated and other-month plans stay out.');

assert(report.includes('selected="">Préventive'));assert(!report.includes('Description de la panne'));assert(!report.includes('>Diagnostic'));console.log('PASS: planned reports default to preventive and hide breakdown fields.');
const readonlyModel={...multiModel,readOnly:true,user:{name:'Responsable',role:'manager',site:'other-site'},tab:'Magasin',selected:null,displayedParts:[{id:'p1',name:'Roulement',reference:'6200',minimum:2}],sites:[{id:'site1',name:'Site 1'}],setModal(){},records:multiModel.records};
const readonlyCalendar=renderToStaticMarkup(React.createElement(RoutineCalendar,{model:readonlyModel,routines,done:[],plans:[plan],canCreate:false,canManage:false,readOnly:true,onOpenPlan(){},onReportPlan(){},onSaved:async()=>{}}));assert(!readonlyCalendar.includes('Ajouter une tâche'));assert(!readonlyCalendar.includes('Intervention réalisée'));assert.match(readonlyCalendar,/disabled=""[^>]*>Fait/);
const {StockView}=load('app/maintenance/stock.tsx');const readonlyStock=renderToStaticMarkup(React.createElement(StockView,{model:readonlyModel}));assert(readonlyStock.includes('Roulement'));assert(!readonlyStock.includes('>Entrée'));assert(!readonlyStock.includes('>Sortie'));assert(!readonlyStock.includes('Modifier le minimum'));
const {OrdersView}=load('app/maintenance/orders.tsx');const readonlyOrders=renderToStaticMarkup(React.createElement(OrdersView,{model:{...readonlyModel,tab:'Devis & achats'}}));assert(readonlyOrders.includes('Fiche / PDF'));assert(!readonlyOrders.includes('Marquer reçu'));
const {InterventionHistory}=load('app/interventions/history.tsx');const readonlyHistory=renderToStaticMarkup(React.createElement(InterventionHistory,{site:'site1',siteName:'Site 1',userRole:'manager',readOnly:true,onSessionChanged(){}}));assert(!readonlyHistory.includes('Nouvelle intervention'));assert(!readonlyHistory.includes('Modifier le formulaire'));
const {MachineDocuments}=load('app/maintenance/machine-documents.tsx');const readonlyDocuments=renderToStaticMarkup(React.createElement(MachineDocuments,{machine:'m1',readOnly:true,onSessionChanged(){}}));assert(!readonlyDocuments.includes('type="file"'));assert(!readonlyDocuments.includes('Ajouter le PDF'));
const {DeletePlanning}=load('app/planning/controls.tsx');const deleteControl=renderToStaticMarkup(React.createElement(DeletePlanning,{model:multiModel,item:plan,kind:'plan',onDeleted:async()=>{}}));assert(deleteControl.includes('Supprimer l’intervention planifiée'));
console.log('PASS: cross-site read-only calendar, stock, quotes, reports and documents hide/block write controls; planning deletion is visible.');
