import { env } from 'cloudflare:workers';
import { database } from '../store';
import { AppError,allowSite,digest,type User } from '../auth';
import { validSite } from '../maintenance/repository';
const hex=(bytes:Uint8Array)=>Array.from(bytes,n=>n.toString(16).padStart(2,'0')).join('');
const bytes=(value:string)=>new Uint8Array(value.match(/.{2}/g)!.map(x=>parseInt(x,16)));
export function appOrigin(){const origin=(env as unknown as Record<string,string>).APP_ORIGIN;if(!/^https:\/\/[^/]+$/.test(origin||''))throw new AppError('Adresse de l’application indisponible.',503);return origin;}
async function encryptionKey(){const secret=(env as unknown as Record<string,string>).MAIL_CONFIG_ENCRYPTION_KEY;if(!secret||!/^[a-f0-9]{64}$/.test(secret))throw new AppError('Stockage sécurisé indisponible.',503);return crypto.subtle.importKey('raw',bytes(secret),'AES-GCM',false,['encrypt','decrypt']);}
export async function readSecret(id:string){const row=await database().prepare('SELECT * FROM mail_configuration WHERE id=?').bind(id).first<any>();if(!row)return null;try{const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes(row.nonce),additionalData:new TextEncoder().encode(id)},await encryptionKey(),bytes(row.cipher));return {...JSON.parse(new TextDecoder().decode(plain)),revision:row.revision,sender:row.sender};}catch{throw new AppError('Connexion mail illisible. Reconnectez la boîte.',503);}}
export async function writeSecret(id:string,value:any,sender:string,revision:number){const iv=crypto.getRandomValues(new Uint8Array(12)),cipher=hex(new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode(id)},await encryptionKey(),new TextEncoder().encode(JSON.stringify(value)))));const result=revision===0?await database().prepare('INSERT OR IGNORE INTO mail_configuration(id,cipher,nonce,sender,revision) VALUES(?,?,?,?,1)').bind(id,cipher,hex(iv),sender).run():await database().prepare('UPDATE mail_configuration SET cipher=?,nonce=?,sender=?,revision=revision+1 WHERE id=? AND revision=?').bind(cipher,hex(iv),sender,id,revision).run();if(!result.meta.changes)throw new AppError('La configuration a changé. Rechargez-la.',409);}
export async function connectionId(user:User,site:string,purpose:string){if(!['admin','director','manager'].includes(user.role))throw new AppError('Accès réservé à l’encadrement.',403);if(!['automatic','quote'].includes(purpose))throw new AppError('Usage mail invalide.');if(site){allowSite(user,site);await validSite(site);}else if(user.role==='manager'||purpose==='quote')throw new AppError('Choisissez votre site.',403);return purpose+':'+(site||'global');}
export async function mailConfigurationStatus(user:User,site='',purpose='automatic'){const id=await connectionId(user,site,purpose),row=await database().prepare('SELECT sender,revision FROM mail_configuration WHERE id=?').bind(id).first<any>(),client=await database().prepare("SELECT revision FROM mail_configuration WHERE id='microsoft-client'").first<any>();return {connected:!!row,sender:row?.sender||'',revision:row?.revision||0,clientConfigured:!!client,clientRevision:client?.revision||0,canConfigureClient:['admin','director'].includes(user.role),redirectUri:appOrigin()+'/api/mail/microsoft/callback'};}
const isGuid=(v:unknown)=>typeof v==='string'&&/^[a-f0-9]{8}-(?:[a-f0-9]{4}-){3}[a-f0-9]{12}$/i.test(v);
const microsoftScopes='openid email offline_access https://graph.microsoft.com/User.Read https://graph.microsoft.com/Mail.Send';
export async function saveMicrosoftClient(user:User,input:any){if(!['admin','director'].includes(user.role))throw new AppError('Configuration Microsoft réservée à l’admin et au directeur.',403);if(typeof input.clientId!=='string'||!isGuid(input.clientId)||typeof input.clientSecret!=='string'||input.clientSecret.length<10||input.clientSecret.length>300||!Number.isInteger(input.revision)||!isGuid(input.tenantId))throw new AppError('Identifiants Microsoft invalides.');await writeSecret('microsoft-client',{clientId:input.clientId,clientSecret:input.clientSecret,tenantId:input.tenantId},'',input.revision);await database().prepare('DELETE FROM mail_oauth_states').run();return {ok:true,message:'Configuration Microsoft enregistrée. Connectez maintenant une boîte Outlook.'};}
export async function startMicrosoftConnection(user:User,site:string,purpose:string){const id=await connectionId(user,site,purpose),client=await readSecret('microsoft-client');if(!client)throw new AppError('Le directeur doit d’abord configurer la connexion Microsoft.');const existing=await database().prepare('SELECT revision FROM mail_configuration WHERE id=?').bind(id).first<any>(),token=hex(crypto.getRandomValues(new Uint8Array(32))),verifier=hex(crypto.getRandomValues(new Uint8Array(32))),hash=await digest(token);await database().prepare('DELETE FROM mail_oauth_states WHERE expires<? OR user_id=?').bind(Date.now(),user.id).run();await database().prepare('INSERT INTO mail_oauth_states(hash,user_id,connection_id,revision,verifier,expires) VALUES(?,?,?,?,?,?)').bind(hash,user.id,id,existing?.revision||0,verifier,Date.now()+600000).run();const challenge=btoa(String.fromCharCode(...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier))))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');const url=new URL('https://login.microsoftonline.com/'+client.tenantId+'/oauth2/v2.0/authorize');url.search=new URLSearchParams({client_id:client.clientId,redirect_uri:appOrigin()+'/api/mail/microsoft/callback',response_type:'code',scope:microsoftScopes,response_mode:'query',prompt:'select_account',state:token,code_challenge:challenge,code_challenge_method:'S256'}).toString();return {url:url.toString(),token};}
export async function microsoftRequest(url:string,body:URLSearchParams){let response:Response;try{response=await fetch(url,{method:'POST',body,signal:AbortSignal.timeout(12000)});}catch{throw new AppError('Microsoft est momentanément indisponible.',503);}const result:any=await response.json().catch(()=>null);if(!response.ok||!result)throw new AppError('Autorisation Microsoft refusée ou expirée. Reconnectez la boîte.',503);return result;}
export async function finishMicrosoftConnection(user:User,state:string,cookie:string,code:string){if(!/^[a-f0-9]{64}$/.test(state)||state!==cookie||!code||code.length>4096)throw new AppError('Connexion Microsoft invalide ou expirée.');const db=database(),hash=await digest(state),row=await db.prepare('SELECT * FROM mail_oauth_states WHERE hash=? AND user_id=? AND expires>?').bind(hash,user.id,Date.now()).first<any>();if(!row)throw new AppError('Connexion Microsoft invalide ou expirée.');const [purpose,scope]=row.connection_id.split(':');await connectionId(user,scope==='global'?'':scope,purpose);const consumed=await db.prepare('DELETE FROM mail_oauth_states WHERE hash=? RETURNING hash').bind(hash).all<any>();if(!consumed.results.length)throw new AppError('Autorisation déjà utilisée.');const client=await readSecret('microsoft-client');if(!client)throw new AppError('Configuration Microsoft absente.');const result=await microsoftRequest('https://login.microsoftonline.com/'+client.tenantId+'/oauth2/v2.0/token',new URLSearchParams({code,client_id:client.clientId,client_secret:client.clientSecret,redirect_uri:appOrigin()+'/api/mail/microsoft/callback',grant_type:'authorization_code',scope:microsoftScopes,code_verifier:row.verifier}));if(!result.refresh_token||!result.access_token||!String(result.scope||'').split(' ').some((v:string)=>v==='Mail.Send'||v==='https://graph.microsoft.com/Mail.Send'))throw new AppError('Autorisez l’envoi de mails pour connecter la boîte.');let profile:any;try{const r=await fetch('https://graph.microsoft.com/v1.0/me?$select=id,mail,userPrincipalName',{headers:{Authorization:'Bearer '+result.access_token},signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error();profile=await r.json();}catch{throw new AppError('Identité Microsoft indisponible.',503);}const email=profile.mail||profile.userPrincipalName;if(typeof profile.id!=='string'||typeof email!=='string'||!/^[^\s<>@]+@[^\s<>@]+\.[^\s<>@]+$/.test(email))throw new AppError('Adresse Microsoft non confirmée.');await writeSecret(row.connection_id,{refreshToken:result.refresh_token,clientId:client.clientId,clientSecret:client.clientSecret,tenantId:client.tenantId,accountId:profile.id},email.toLowerCase(),row.revision);return {sender:email};}
export async function disconnectMail(user:User,site:string,purpose:string,revision:number){const id=await connectionId(user,site,purpose),result=await database().prepare('DELETE FROM mail_configuration WHERE id=? AND revision=?').bind(id,revision).run();if(!result.meta.changes)throw new AppError('La connexion a changé. Rechargez-la.',409);await database().prepare('DELETE FROM mail_oauth_states WHERE connection_id=?').bind(id).run();return {ok:true,message:'Boîte déconnectée de la GMAO.'};}
// Global default; a site connection overrides it. Quotes may have a separate mailbox.
export async function readMailConfiguration(site='',purpose='automatic'){const ids=purpose==='quote'?['quote:'+site,'automatic:'+site,'automatic:global']:['automatic:'+site,'automatic:global'];for(const id of [...new Set(ids)]){const config=await readSecret(id);if(config)return {...config,id};}return null;}
export async function anyMailConnection(category='account'){return !!await database().prepare("SELECT id FROM mail_configuration WHERE id LIKE 'automatic:%' OR (?='quote' AND id LIKE 'quote:%')").bind(category).first();}
