'use client';
import { useState } from 'react';
import type { User } from '../lib/auth';
import { Access } from './access';
export function AccountProfile({user,mailReady,onRefresh,onClose}:{user:User;mailReady:boolean;onRefresh:()=>Promise<void>;onClose:()=>void}) {
 const [email,setEmail]=useState(user.email||''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[changePassword,setChangePassword]=useState(false);
 async function request(url:string,init:RequestInit){setBusy(true);setError('');setMessage('');try{
  const r=await fetch(url,init),d:any=await r.json();if(!r.ok)throw Error(d.error);setMessage(d.message||'Modification enregistrée.');setPassword('');await onRefresh();
 }catch(e){setError(e instanceof Error?e.message:'Modification impossible.');}finally{setBusy(false);}}
 if(changePassword)return <><Access user={user} onSuccess={()=>{setChangePassword(false);onRefresh();}}/><button className="account-back" onClick={()=>setChangePassword(false)}>Retour à mon profil</button></>;
 return <div className="access-screen"><section className="access-card profile-card"><div className="panel-head"><h1>Mon profil</h1>{(user.email||!!user.test_account)&&<button onClick={onClose}>Retour à la GMAO</button>}</div><p>{user.name} · {user.username}</p>{!user.email&&<p>{user.test_account?'Compte de test : l’adresse mail est facultative. Sans adresse, vous ne recevrez pas de rappels et la récupération du mot de passe se fera auprès de l’admin ou du directeur.':'Renseignez votre adresse mail pour accéder à l’application.'}</p>}
 <div className="profile-avatar">{user.avatar_key?<img alt="Votre photo de profil" src={'/api/profile/avatar?v='+user.avatar_version}/>:<span aria-label="Aucune photo">{user.name.slice(0,1)}</span>}<label>Photo de profil<input disabled={busy} type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file){const form=new FormData();form.set('file',file);request('/api/profile/avatar',{method:'POST',body:form});}e.target.value='';}}/><small>PNG, JPEG ou WebP · 2 Mo maximum.</small></label>{user.avatar_key&&<button disabled={busy} onClick={()=>request('/api/profile/avatar',{method:'DELETE'})}>Retirer la photo</button>}</div>
 <form onSubmit={e=>{e.preventDefault();request('/api/profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,currentPassword:password})});}}><label>Adresse mail<input required type="email" maxLength={254} autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} disabled={busy}/></label><label>Mot de passe actuel<input required type="password" maxLength={128} autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} disabled={busy}/><small>Confirme votre identité pour changer votre adresse mail.</small></label><button className="primary" disabled={busy}>Enregistrer mon adresse mail</button></form>
 {user.email&&<p>{user.email_verified?'Adresse mail confirmée.':'Adresse mail à confirmer.'}</p>}{!mailReady&&<p className="muted">L’envoi des mails n’est pas encore activé. Votre adresse peut déjà être enregistrée.</p>}{user.email&&!user.email_verified&&<button disabled={busy||!mailReady} onClick={()=>request('/api/account-links',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'verify-send'})})}>Envoyer le lien de confirmation</button>}
 <button disabled={busy} onClick={()=>setChangePassword(true)}>Changer mon mot de passe</button>{message&&<p role="status">{message}</p>}{error&&<p className="error" role="alert">{error}</p>}<button onClick={async()=>{await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});onRefresh();}}>Déconnexion</button>
 </section></div>;
}
